import 'mapbox-gl/dist/mapbox-gl.css';
import { Inter, Playfair_Display } from 'next/font/google';
import { Metadata } from 'next/types';
import { ReactNode } from 'react';

import '@/styles/style.css';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair-display',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  generator: 'Page generator',
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="fr">
      <body
        className={`${inter.variable} ${playfair.variable} font-inter antialiased bg-white text-slate-800 tracking-tight`}
      >
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
